export const BUCKETLIST_SHOW_RESET = 'BUCKETLIST_SHOW_RESET'
export const BUCKETLIST_SHOW_SET_ERROR = 'BUCKETLIST_SHOW_SET_ERROR'
export const BUCKETLIST_SHOW_SET_RETRIEVED = 'BUCKETLIST_SHOW_SET_RETRIEVED'
export const BUCKETLIST_SHOW_TOGGLE_LOADING = 'BUCKETLIST_SHOW_TOGGLE_LOADING'
