export const BUCKETLIST_DELETE_RESET = 'BUCKETLIST_DELETE_RESET'
export const BUCKETLIST_DELETE_SET_ERROR = 'BUCKETLIST_DELETE_SET_ERROR'
export const BUCKETLIST_DELETE_SET_DELETED = 'BUCKETLIST_DELETE_SET_DELETED'
export const BUCKETLIST_DELETE_TOGGLE_LOADING = 'BUCKETLIST_DELETE_TOGGLE_LOADING'
